[2025-04-14T22:07:22.575+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T22:07:22.580+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_trends_etl_pipeline.extract_google_trends_data manual__2025-04-14T14:00:08.068917+00:00 [queued]>
[2025-04-14T22:07:22.583+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_trends_etl_pipeline.extract_google_trends_data manual__2025-04-14T14:00:08.068917+00:00 [queued]>
[2025-04-14T22:07:22.583+0800] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-14T22:07:22.594+0800] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_google_trends_data> on 2025-04-14 14:00:08.068917+00:00
[2025-04-14T22:07:22.596+0800] {standard_task_runner.py:72} INFO - Started process 15329 to run task
[2025-04-14T22:07:22.599+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'google_trends_etl_pipeline', 'extract_google_trends_data', 'manual__2025-04-14T14:00:08.068917+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/google_trends_dag.py', '--cfg-path', '/tmp/tmp3q_4ta3_']
[2025-04-14T22:07:22.599+0800] {standard_task_runner.py:105} INFO - Job 67: Subtask extract_google_trends_data
[2025-04-14T22:07:22.628+0800] {task_command.py:467} INFO - Running <TaskInstance: google_trends_etl_pipeline.extract_google_trends_data manual__2025-04-14T14:00:08.068917+00:00 [running]> on host Conglaptop.
[2025-04-14T22:07:22.665+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='google_trends_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_google_trends_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T14:00:08.068917+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-14T14:00:08.068917+00:00'
[2025-04-14T22:07:22.666+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T22:07:22.666+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T22:07:22.666+0800] {logging_mixin.py:190} INFO - Current task name:extract_google_trends_data state:running start_date:2025-04-14 14:07:22.580686+00:00
[2025-04-14T22:07:22.666+0800] {logging_mixin.py:190} INFO - Dag name:google_trends_etl_pipeline and current dag run status:running
[2025-04-14T22:07:22.667+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T22:07:23.524+0800] {logging_mixin.py:190} INFO - {'version': '0.1.20241227', 'status_code': 20000, 'status_message': 'Ok.', 'time': '0.0489 sec.', 'cost': 0.00225, 'tasks_count': 1, 'tasks_error': 0, 'tasks': [{'id': '04141707-9519-0170-0000-37d430f71678', 'status_code': 20100, 'status_message': 'Task Created.', 'time': '0.0053 sec.', 'cost': 0.00225, 'result_count': 0, 'path': ['v3', 'keywords_data', 'google_trends', 'explore', 'task_post'], 'data': {'api': 'keywords_data', 'function': 'explore', 'se': 'google_trends', 'date_from': '2025-03-01', 'date_to': '2025-03-31', 'keywords': ['Singapore', 'Thailand', 'Malaysia', 'Indonesia', 'Vietnam'], 'category_code': 67}, 'result': None}]}
[2025-04-14T22:07:24.397+0800] {logging_mixin.py:190} INFO - {'version': '0.1.20241227', 'status_code': 20000, 'status_message': 'Ok.', 'time': '0.0635 sec.', 'cost': 0.00225, 'tasks_count': 1, 'tasks_error': 0, 'tasks': [{'id': '04141707-9519-0170-0000-9ee244a97717', 'status_code': 20100, 'status_message': 'Task Created.', 'time': '0.0045 sec.', 'cost': 0.00225, 'result_count': 0, 'path': ['v3', 'keywords_data', 'google_trends', 'explore', 'task_post'], 'data': {'api': 'keywords_data', 'function': 'explore', 'se': 'google_trends', 'date_from': '2025-03-01', 'date_to': '2025-03-31', 'keywords': ['Singapore', 'Philippines', 'Cambodia', 'Myanmar'], 'category_code': 67}, 'result': None}]}
[2025-04-14T22:07:25.279+0800] {logging_mixin.py:190} INFO - {'version': '0.1.20241227', 'status_code': 20000, 'status_message': 'Ok.', 'time': '0.0523 sec.', 'cost': 0.00225, 'tasks_count': 1, 'tasks_error': 0, 'tasks': [{'id': '04141707-9519-0170-0000-c5e26d72bfff', 'status_code': 20100, 'status_message': 'Task Created.', 'time': '0.0065 sec.', 'cost': 0.00225, 'result_count': 0, 'path': ['v3', 'keywords_data', 'google_trends', 'explore', 'task_post'], 'data': {'api': 'keywords_data', 'function': 'explore', 'se': 'google_trends', 'date_from': '2025-03-01', 'date_to': '2025-03-31', 'keywords': ['Singapore', 'Laos', 'Brunei'], 'category_code': 67}, 'result': None}]}
[2025-04-14T22:07:25.280+0800] {logging_mixin.py:190} INFO - Waiting 60 seconds for tasks to complete...
[2025-04-14T22:08:26.261+0800] {logging_mixin.py:190} INFO - 1
[2025-04-14T22:08:26.262+0800] {logging_mixin.py:190} INFO - []
[2025-04-14T22:08:26.262+0800] {logging_mixin.py:190} INFO - Results fetched successfully.
[2025-04-14T22:08:26.266+0800] {logging_mixin.py:190} INFO - No data was retrieved. Please check if the tasks returned any results.
[2025-04-14T22:08:26.266+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/airflow/dags/google_trends_dag.py", line 74, in extract_google_trends_data
    raise ValueError("No Google Trends data was extracted")
ValueError: No Google Trends data was extracted
[2025-04-14T22:08:26.269+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-14T22:08:26.270+0800] {logging_mixin.py:190} INFO - Task start:2025-04-14 14:07:22.580686+00:00 end:2025-04-14 14:08:26.269519+00:00 duration:63.688833
[2025-04-14T22:08:26.270+0800] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_google_trends_data> dag:<DAG: google_trends_etl_pipeline> dagrun:<DagRun google_trends_etl_pipeline @ 2025-04-14 14:00:08.068917+00:00: manual__2025-04-14T14:00:08.068917+00:00, state:running, queued_at: 2025-04-14 14:00:08.085687+00:00. externally triggered: True>
[2025-04-14T22:08:26.270+0800] {logging_mixin.py:190} INFO - Failure caused by No Google Trends data was extracted
[2025-04-14T22:08:26.270+0800] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=google_trends_etl_pipeline, task_id=extract_google_trends_data, run_id=manual__2025-04-14T14:00:08.068917+00:00, execution_date=20250414T140008, start_date=20250414T140722, end_date=20250414T140826
[2025-04-14T22:08:26.295+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T22:08:26.295+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 67 for task extract_google_trends_data (No Google Trends data was extracted; 15329)
Traceback (most recent call last):
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/airflow/dags/google_trends_dag.py", line 74, in extract_google_trends_data
    raise ValueError("No Google Trends data was extracted")
ValueError: No Google Trends data was extracted
[2025-04-14T22:08:26.336+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-14T22:08:26.348+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T22:08:26.356+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
