[2025-04-14T22:03:50.835+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T22:03:50.842+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_trends_etl_pipeline.extract_google_trends_data manual__2025-04-14T14:03:47.347599+00:00 [queued]>
[2025-04-14T22:03:50.846+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_trends_etl_pipeline.extract_google_trends_data manual__2025-04-14T14:03:47.347599+00:00 [queued]>
[2025-04-14T22:03:50.846+0800] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T22:03:50.859+0800] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_google_trends_data> on 2025-04-14 14:03:47.347599+00:00
[2025-04-14T22:03:50.862+0800] {standard_task_runner.py:72} INFO - Started process 14045 to run task
[2025-04-14T22:03:50.865+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'google_trends_etl_pipeline', 'extract_google_trends_data', 'manual__2025-04-14T14:03:47.347599+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/google_trends_dag.py', '--cfg-path', '/tmp/tmplcf9n45d']
[2025-04-14T22:03:50.866+0800] {standard_task_runner.py:105} INFO - Job 66: Subtask extract_google_trends_data
[2025-04-14T22:03:50.897+0800] {task_command.py:467} INFO - Running <TaskInstance: google_trends_etl_pipeline.extract_google_trends_data manual__2025-04-14T14:03:47.347599+00:00 [running]> on host Conglaptop.
[2025-04-14T22:03:50.945+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='google_trends_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_google_trends_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T14:03:47.347599+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-14T14:03:47.347599+00:00'
[2025-04-14T22:03:50.946+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T22:03:50.946+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T22:03:50.946+0800] {logging_mixin.py:190} INFO - Current task name:extract_google_trends_data state:running start_date:2025-04-14 14:03:50.843255+00:00
[2025-04-14T22:03:50.947+0800] {logging_mixin.py:190} INFO - Dag name:google_trends_etl_pipeline and current dag run status:running
[2025-04-14T22:03:50.947+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T22:03:51.862+0800] {logging_mixin.py:190} INFO - {'version': '0.1.20241227', 'status_code': 20000, 'status_message': 'Ok.', 'time': '0.0688 sec.', 'cost': 0.00225, 'tasks_count': 1, 'tasks_error': 0, 'tasks': [{'id': '04141703-9519-0170-0000-d2bdbedec3bf', 'status_code': 20100, 'status_message': 'Task Created.', 'time': '0.0085 sec.', 'cost': 0.00225, 'result_count': 0, 'path': ['v3', 'keywords_data', 'google_trends', 'explore', 'task_post'], 'data': {'api': 'keywords_data', 'function': 'explore', 'se': 'google_trends', 'date_from': '2025-03-01', 'date_to': '2025-03-31', 'keywords': ['Singapore', 'Thailand', 'Malaysia', 'Indonesia', 'Vietnam'], 'category_code': 67}, 'result': None}]}
[2025-04-14T22:03:52.888+0800] {logging_mixin.py:190} INFO - {'version': '0.1.20241227', 'status_code': 20000, 'status_message': 'Ok.', 'time': '0.1037 sec.', 'cost': 0.00225, 'tasks_count': 1, 'tasks_error': 0, 'tasks': [{'id': '04141703-9519-0170-0000-81d2c1b7f2a5', 'status_code': 20100, 'status_message': 'Task Created.', 'time': '0.0136 sec.', 'cost': 0.00225, 'result_count': 0, 'path': ['v3', 'keywords_data', 'google_trends', 'explore', 'task_post'], 'data': {'api': 'keywords_data', 'function': 'explore', 'se': 'google_trends', 'date_from': '2025-03-01', 'date_to': '2025-03-31', 'keywords': ['Singapore', 'Philippines', 'Cambodia', 'Myanmar'], 'category_code': 67}, 'result': None}]}
[2025-04-14T22:03:53.782+0800] {logging_mixin.py:190} INFO - {'version': '0.1.20241227', 'status_code': 20000, 'status_message': 'Ok.', 'time': '0.0689 sec.', 'cost': 0.00225, 'tasks_count': 1, 'tasks_error': 0, 'tasks': [{'id': '04141703-9519-0170-0000-8777891ee910', 'status_code': 20100, 'status_message': 'Task Created.', 'time': '0.0097 sec.', 'cost': 0.00225, 'result_count': 0, 'path': ['v3', 'keywords_data', 'google_trends', 'explore', 'task_post'], 'data': {'api': 'keywords_data', 'function': 'explore', 'se': 'google_trends', 'date_from': '2025-03-01', 'date_to': '2025-03-31', 'keywords': ['Singapore', 'Laos', 'Brunei'], 'category_code': 67}, 'result': None}]}
[2025-04-14T22:03:53.783+0800] {logging_mixin.py:190} INFO - Waiting 60 seconds for tasks to complete...
[2025-04-14T22:04:54.887+0800] {logging_mixin.py:190} INFO - 1
[2025-04-14T22:04:54.889+0800] {logging_mixin.py:190} INFO - []
[2025-04-14T22:04:54.890+0800] {logging_mixin.py:190} INFO - Results fetched successfully.
[2025-04-14T22:04:54.898+0800] {logging_mixin.py:190} INFO - No data was retrieved. Please check if the tasks returned any results.
[2025-04-14T22:04:54.899+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/airflow/dags/google_trends_dag.py", line 74, in extract_google_trends_data
    raise ValueError("No Google Trends data was extracted")
ValueError: No Google Trends data was extracted
[2025-04-14T22:04:54.905+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-14T22:04:54.906+0800] {logging_mixin.py:190} INFO - Task start:2025-04-14 14:03:50.843255+00:00 end:2025-04-14 14:04:54.905589+00:00 duration:64.062334
[2025-04-14T22:04:54.906+0800] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_google_trends_data> dag:<DAG: google_trends_etl_pipeline> dagrun:<DagRun google_trends_etl_pipeline @ 2025-04-14 14:03:47.347599+00:00: manual__2025-04-14T14:03:47.347599+00:00, state:running, queued_at: 2025-04-14 14:03:47.357071+00:00. externally triggered: True>
[2025-04-14T22:04:54.906+0800] {logging_mixin.py:190} INFO - Failure caused by No Google Trends data was extracted
[2025-04-14T22:04:54.906+0800] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=google_trends_etl_pipeline, task_id=extract_google_trends_data, run_id=manual__2025-04-14T14:03:47.347599+00:00, execution_date=20250414T140347, start_date=20250414T140350, end_date=20250414T140454
[2025-04-14T22:04:54.932+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T22:04:54.932+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 66 for task extract_google_trends_data (No Google Trends data was extracted; 14045)
Traceback (most recent call last):
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/airflow/dags/google_trends_dag.py", line 74, in extract_google_trends_data
    raise ValueError("No Google Trends data was extracted")
ValueError: No Google Trends data was extracted
[2025-04-14T22:04:54.952+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-14T22:04:54.959+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T22:04:54.960+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
